### PR TITLE
fix: support TypeScript 4.8

### PR DESCRIPTION
**Pull request by SimenB**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Similar to https://github.com/fastify/fastify/pull/4222

### CODE REVIEW

**Comment by SimenB** [comment]
Instead of pinging in each issue, I'll just post a list here with modules that are stuck on v3 and won't get this update (probably more, but these are the ones in my project)

https://github.com/fastify/fastify-accepts/pull/137
https://github.com/fastify/fastify-compress/pull/239
https://github.com/fastify/fastify-express/pull/92
https://github.com/fastify/fastify-formbody/pull/122
https://github.com/fastify/fastify-multipart/pull/371

**Review by kibertoad — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
all modules released too

**Comment by SimenB** [comment]
Awesome, thanks @mcollina!

**Comment by SimenB** [comment]
Missing the ones I pinged in btw (before listing here): https://github.com/fastify/fastify-nextjs/pull/591 & https://github.com/fastify/fastify-sensible/pull/119

**Pull request merged**
