### PR TITLE
fixes regex patterns on typescript files

### PR DESCRIPTION
**Pull request by fox1t**
Now fails silently on no match case

### CODE REVIEW

**Comment by fox1t** [comment]
It is ok for you if i add ts-node as devDep in order to add .ts tests?

**Comment by fox1t** [comment]
The "bug" started because TS devs during development, usually, use ts-node so no real compilation with .js files emit is needed. If we want to test this case, i think we need ts-node. 
As you can see on https://github.com/fastify/fastify-plugin/issues/38 stacktrace has .ts files in it.

**Comment by fox1t** [comment]
Just to clarify one more thing: the case of .ts -> .js compiled files is already handled by tests included.

**Comment by fox1t** [comment]
I found this issue https://github.com/tapjs/node-tap/issues/313 on tap and typescript. Since we need to test ts-node we have to use it to run .test.ts scripts. I followed what https://github.com/tapjs/node-tap/issues/313#issuecomment-245441839 says.

**Comment by fox1t** [comment]
Ok, it is not working. It is the same as `require('ts-node').register()`, that I already tried before hash bang thing. 
It just says
```
❯ npm run test-ts

> fastify-plugin@1.1.2 test-ts /Users/maksim/Projects/fox1t/fastify-plugin
> tap test/composite.test.ts

total ................................................. 0/0

  0 passing (3.805ms)

  ok
```
Is that a tap limitation?

**Comment by mcollina** [comment]
Oh I'm sorry, you should change the extension of `test/composite.test.ts` to ` test/composite.test.js`.

**Comment by fox1t** [comment]
@mcollina you made it. I fexed with .js extension and now works like a charm.
👍

**Pull request merged**
