### PR TITLE
chore: fastify v4 compatibility

### PR DESCRIPTION
**Pull request by simoneb**
This PR introduces the (non functional) changes needed to make this package work with Fastify v4 (only docs and tests). Notes this uses as merge base the dependabot branch.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by simoneb** [comment]
if somebody could merge this PR then we can check that the dependabot one also works and then do a release

**Comment by simoneb** [comment]
btw this repo could be under the fastify-plugins team umbrella, and I could do those things myself if it was :)

**Comment by jsumners** [comment]
This would be under the `libraries` team, as this isn't really a plugin. I can make that happen and get you on that team. Agreed, @mcollina ?

**Comment by simoneb** [comment]
oh ok gotcha, I didn't know there was another team for this. I don't mind, I not contributing that often around here anyway

**Comment by jsumners** [comment]
Done. I have some work to do with getting some other libraries into the npm org, but this one is there.

**Pull request merged**
