### PR TITLE
Merge `next` into `master`

### PR DESCRIPTION
**Pull request by jsumners**
As titled.

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
CI is failing

**Comment by jsumners** [comment]
For some reason npm keeps installing the `alpha.1` release of Fastify and I just don't have the patience to figure it out today. I'll come back later.

**Comment by jsumners** [comment]
The only way I could figure out to fix the problem was to mark the mislabeled `fastify@5.0.0-aplha.1` version as deprecated.

**Review by lilpoozie2005 — APPROVED** [review]

**Pull request merged**
